"""add cuisine_type to menus

Revision ID: d7f46fcaacab
Revises: 0001_create_menus
Create Date: 2026-05-28 10:03:36.015815

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd7f46fcaacab'
down_revision: str | None = '0001_create_menus'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('menus', sa.Column('cuisine_type', sa.String(length=100), server_default='', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('menus', 'cuisine_type')
    # ### end Alembic commands ###
