"""Pydantic schemas for menus."""
from datetime import datetime
from typing import Literal
from uuid import UUID

from pydantic import BaseModel, ConfigDict, Field

from app.schemas.dish import Dish

# Menu-level extraction status. "extracting" while OCR + translation runs in the
# background; "ready" once dishes are available; "failed" if extraction errored.
MenuStatus = Literal["extracting", "ready", "failed"]


class MenuCreate(BaseModel):
    """Internal model used between extraction service and persistence."""

    source_language: str = Field(..., description="ISO language code: de, en, it, etc.")
    dishes: list[Dish]
    restaurant_name: str | None = None
    cuisine_type: str | None = Field(
        default=None,
        description="Human-readable cuisine style, e.g. 'Italian', 'Japanese'. "
                    "Generated by Gemini during extraction.",
    )


class Menu(BaseModel):
    """Public API response for a menu."""

    id: UUID
    source_language: str = Field(..., description="ISO language code: de, en, it, etc.")
    restaurant_name: str | None = None
    cuisine_type: str | None = None
    dishes: list[Dish]
    status: MenuStatus = Field(
        default="ready",
        description="Extraction status. Clients poll while 'extracting'.",
    )
    created_at: datetime

    model_config = ConfigDict(from_attributes=True)
